Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
#  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.network "private_network", ip: "192.168.56.200"
  config.vm.provider "virtualbox" do |vb|
  #config.vm.synced_folder ".", "/home/vagrant/", :nfs => { :mount_options => ["dmode=777", "fmode=666"] }
  config.vm.provision "shell", path: "bootstrap.sh"
  vb.memory = "1024"
  
 end
end
